pub use crate::tags::{
    a::A,
    body::body_node::BodyNode,
    body::Body,
    br::Br,
    div::Div,
    form::Form,
    head::Head,
    headings::{H1, H2, H3, H4, H5, H6},
    html::Html,
    input::Input,
    label::Label,
    meta::Meta,
    option::SelectOption,
    p::P,
    select::Select,
    title::Title,
};
